name: Price Tracker

on:
  schedule:
    - cron: "0 */5 * * *"    # every 5 hours (UTC)
  workflow_dispatch:          # allow manual trigger

jobs:
  check-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Optional random delay (0–10 minutes)
      - name: Random sleep
        run: sleep $((RANDOM % 600))

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Restore state.json from secret
        run: echo "${{ secrets.STATE_B64 }}" | base64 --decode > state.json
        shell: bash

      - name: Run tracker
        run: python tracker.py

      - name: Upload screenshots (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
